# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/work/AD4134/vivado/ad4134fw.runs/synth_1/ad4134fw_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/work/AD4134/vivado/ad4134fw.cache/wt [current_project]
set_property parent.project_path C:/work/AD4134/vivado/ad4134fw.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/work/AD4134/vivado/ad4134fw.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib C:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/hdl/ad4134fw_wrapper.vhd
add_files C:/work/AD4134/vivado/ad4134fw.srcs/sources_1/bd/ad4134fw/ad4134fw.bd
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_processing_system7_0_0/ad4134fw_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_proc_sys_reset_0_0/ad4134fw_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_proc_sys_reset_0_0/ad4134fw_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_proc_sys_reset_0_0/ad4134fw_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_clk_wiz_0_0/ad4134fw_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_clk_wiz_0_0/ad4134fw_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_clk_wiz_0_0/ad4134fw_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_1/bd_5956_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_1/bd_5956_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_2/bd_5956_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_3/bd_5956_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_4/bd_5956_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_5/bd_5956_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_6/bd_5956_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_10/bd_5956_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_11/bd_5956_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_12/bd_5956_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_13/bd_5956_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_14/bd_5956_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_15/bd_5956_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_16/bd_5956_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_17/bd_5956_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_18/bd_5956_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_19/bd_5956_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_20/bd_5956_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_21/bd_5956_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_23/bd_5956_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_24/bd_5956_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_25/bd_5956_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_26/bd_5956_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_27/bd_5956_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_28/bd_5956_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_30/bd_5956_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_31/bd_5956_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_32/bd_5956_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_33/bd_5956_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_34/bd_5956_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_35/bd_5956_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_37/bd_5956_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_38/bd_5956_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_39/bd_5956_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_40/bd_5956_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_41/bd_5956_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/bd_0/ip/ip_42/bd_5956_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_c_counter_binary_0_0/ad4134fw_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_axi_gpio_0_0/ad4134fw_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_axi_gpio_0_0/ad4134fw_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_axi_gpio_0_0/ad4134fw_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_blk_mem_gen_0_0/ad4134fw_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_axi_bram_ctrl_0_0/ad4134fw_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_axi_gpio_0_1/ad4134fw_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_axi_gpio_0_1/ad4134fw_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_axi_gpio_0_1/ad4134fw_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_blk_mem_gen_0_2/ad4134fw_blk_mem_gen_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_axi_bram_ctrl_0_2/ad4134fw_axi_bram_ctrl_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ad4134fw_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/work/AD4134/constraints/io.xdc
set_property used_in_implementation false [get_files C:/work/AD4134/constraints/io.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/work/AD4134/vivado/ad4134fw.srcs/utils_1/imports/synth_1/ad4134fw_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top ad4134fw_wrapper -part xc7z010clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ad4134fw_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file ad4134fw_wrapper_utilization_synth.rpt -pb ad4134fw_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
