# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/work/AD4134/constraints/io.xdc

# Block Designs: bd/ad4134fw/ad4134fw.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad4134fw || ORIG_REF_NAME==ad4134fw} -quiet] -quiet

# IP: bd/ad4134fw/ip/ad4134fw_processing_system7_0_0/ad4134fw_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad4134fw_processing_system7_0_0 || ORIG_REF_NAME==ad4134fw_processing_system7_0_0} -quiet] -quiet

# IP: bd/ad4134fw/ip/ad4134fw_proc_sys_reset_0_0/ad4134fw_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad4134fw_proc_sys_reset_0_0 || ORIG_REF_NAME==ad4134fw_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ad4134fw/ip/ad4134fw_clk_wiz_0_0/ad4134fw_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad4134fw_clk_wiz_0_0 || ORIG_REF_NAME==ad4134fw_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ad4134fw/ip/ad4134fw_smartconnect_0_0/ad4134fw_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad4134fw_smartconnect_0_0 || ORIG_REF_NAME==ad4134fw_smartconnect_0_0} -quiet] -quiet

# IP: bd/ad4134fw/ip/ad4134fw_ad4134_clock_generat_0_0/ad4134fw_ad4134_clock_generat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad4134fw_ad4134_clock_generat_0_0 || ORIG_REF_NAME==ad4134fw_ad4134_clock_generat_0_0} -quiet] -quiet

# IP: bd/ad4134fw/ip/ad4134fw_ad4134_control_0_0/ad4134fw_ad4134_control_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad4134fw_ad4134_control_0_0 || ORIG_REF_NAME==ad4134fw_ad4134_control_0_0} -quiet] -quiet

# IP: bd/ad4134fw/ip/ad4134fw_spi_controller_0_0/ad4134fw_spi_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad4134fw_spi_controller_0_0 || ORIG_REF_NAME==ad4134fw_spi_controller_0_0} -quiet] -quiet

# IP: bd/ad4134fw/ip/ad4134fw_xlslice_0_0/ad4134fw_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad4134fw_xlslice_0_0 || ORIG_REF_NAME==ad4134fw_xlslice_0_0} -quiet] -quiet

# IP: bd/ad4134fw/ip/ad4134fw_xlslice_1_0/ad4134fw_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad4134fw_xlslice_1_0 || ORIG_REF_NAME==ad4134fw_xlslice_1_0} -quiet] -quiet

# IP: bd/ad4134fw/ip/ad4134fw_c_counter_binary_0_0/ad4134fw_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad4134fw_c_counter_binary_0_0 || ORIG_REF_NAME==ad4134fw_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/ad4134fw/ip/ad4134fw_axi_gpio_0_0/ad4134fw_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad4134fw_axi_gpio_0_0 || ORIG_REF_NAME==ad4134fw_axi_gpio_0_0} -quiet] -quiet

# XDC: c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ad4134fw_ooc.xdc
