# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/work/AD4134/vivado/ad4134fw.srcs/sources_1/bd/ad4134fw/ip/ad4134fw_blk_mem_gen_0_0/ad4134fw_blk_mem_gen_0_0.xci
# IP: The module: 'ad4134fw_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_blk_mem_gen_0_0/ad4134fw_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ad4134fw_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/work/AD4134/vivado/ad4134fw.srcs/sources_1/bd/ad4134fw/ip/ad4134fw_blk_mem_gen_0_0/ad4134fw_blk_mem_gen_0_0.xci
# IP: The module: 'ad4134fw_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/work/AD4134/vivado/ad4134fw.gen/sources_1/bd/ad4134fw/ip/ad4134fw_blk_mem_gen_0_0/ad4134fw_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ad4134fw_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
